#######################################################################################################
# Copyright (C) Heap of Battle 2024
# Author: Gaina Stefan
# Date: 11.02.2024
# Description: This Makefile is used to invoke the automated tests.
#######################################################################################################

RUN := ./common/run.sh

all:
	$(RUN) main_menu_quit
	$(RUN) main_menu_exit
