#######################################################################################################
# Copyright (C) Heap of Battle 2024
# Author: Gaina Stefan
# Date: 08.12.2024
# Description: This Makefile is used to invoke the automated test suites.
#######################################################################################################

all:
	python3 test.py ./../../build/debug/bin/hob-log-test tests/smoke_input.txt tests/smoke_output.txt
