#######################################################################################################
# Copyright (C) Heap of Battle 2024
# Author: Gaina Stefan
# Date: 21.01.2024
# Description: This Makefile is used to invoke the Makefiles in the subdirectories.
#######################################################################################################

all:
	$(MAKE) -C hob_ChatFrame
	$(MAKE) -C hob_Component
	$(MAKE) -C hob_Cursor
	$(MAKE) -C hob_Encryptor
	$(MAKE) -C hob_FramesPerSecond
#	$(MAKE) -C hob_Game
	$(MAKE) -C hob_LoadingScreen
	$(MAKE) -C hob_Music
	$(MAKE) -C hob_Ping
	$(MAKE) -C hob_Sound
	$(MAKE) -C hob_Texture
	$(MAKE) -C hob_Window

### RUN TESTS ###
run_tests:
	$(MAKE) run_tests -C hob_ChatFrame
	$(MAKE) run_tests -C hob_Component
	$(MAKE) run_tests -C hob_Cursor
	$(MAKE) run_tests -C hob_Encryptor
	$(MAKE) run_tests -C hob_FramesPerSecond
#	$(MAKE) run_tests -C hob_Game
	$(MAKE) run_tests -C hob_LoadingScreen
	$(MAKE) run_tests -C hob_Music
	$(MAKE) run_tests -C hob_Ping
	$(MAKE) run_tests -C hob_Sound
	$(MAKE) run_tests -C hob_Texture
	$(MAKE) run_tests -C hob_Window

### CLEAN ###
clean:
	$(MAKE) clean -C hob_ChatFrame
	$(MAKE) clean -C hob_Component
	$(MAKE) clean -C hob_Cursor
	$(MAKE) clean -C hob_Encryptor
	$(MAKE) clean -C hob_FramesPerSecond
#	$(MAKE) clean -C hob_Game
	$(MAKE) clean -C hob_LoadingScreen
	$(MAKE) clean -C hob_Music
	$(MAKE) clean -C hob_Ping
	$(MAKE) clean -C hob_Sound
	$(MAKE) clean -C hob_Texture
	$(MAKE) clean -C hob_Window
